import java.util.Random;

class Thread1 extends Thread {
    int count;
    public Thread1(int count) {
        this.count = count;
    }

    public void run() {
        Random random = new Random();
        for (int i = 0; i < count; i++) {
            int number = random.nextInt(10);
            System.out.println("Number Generated by thread1 is: " + number);

            if (number % 2 == 0) {
                new Thread2(number).start();
            } else {
                new Thread3(number).start();
            }

            try {
                Thread.sleep(1000);
            } catch (InterruptedException e) {
                System.out.println("Thread is interrupted during sleep");
            }
        }
        System.out.println("Random number generation completed.");
    }
}

class Thread2 extends Thread {
    private int number;

    public Thread2(int number) {
        this.number = number;
    }

    public void run() {
        System.out.println("Square of " + number + " is: " + (number * number));
    }
}

class Thread3 extends Thread {
    private int number;

    public Thread3(int number) {
        this.number = number;
    }

    public void run() {
        System.out.println("Cube of " + number + " is: " + ((number * number) * number));
    }
}

public class Practical_34 {
    public static void main(String[] args) {
        Thread1 t1 = new Thread1(5);
        t1.start();
 }
}